char *makefileTest =
"{{={% %}=}}TITULO  := makefile generado por  por zConfig1\n"
"NAME    := {%&titulo%}Test\n"
"VERSION := 1.0.0\n"
"\n"
"FUENTES  :=  {%&titulo%}Test.c\n"
"INCLUDES := {%&titulo%}.h\n"
"\n"
"OUTHER_DIR_INCLUDE  :=\n"
"\n"
"OUTHER_DIR_LIBS :=\n"
"\n"
"OUTHER_LIBS :=\n"
"\n"
"PROYECT_LIBS :=lib{%&titulo%}.a\n"
"\n"
"PROGRAM_NAME:= $(NAME)\n"
"CFLAGS = $(OUTHER_DIR_INCLUDE)\n"
"LDFLAGS =  $(OUTHER_DIR_LIB:%=-L%)\n"
"LDLIBS = \n"
"OBJETOS      := $(FUENTES:%.c=%.o)\n"
"\n"
"# -------- RULES ------------------\n"
"\n"
"compila: $(PROGRAM_NAME)\n"
"\n"
"$(OBJETOS):$(FUENTES) $(INCLUDES) $(OUTHER_LIBS)\n"
"\n"
"$(PROGRAM_NAME): $(OBJETOS) $(PROYECT_LIBS)\n"
"clean:\n"
"	- rm -f $(OBJETOS) $(PROGRAM_NAME)\n"
"\n";
