char *makefileMain =
"{{={% %}=}}TITULO  := makefile generado por  zConfig1\n"
"NAME    := {%&titulo%}\n"
"VERSION := 1.0.0\n"
"\n"
"FUENTES  :=  {%&titulo%}Lee.c {%&titulo%}2Json.c {%&titulo%}ParseJson.c cJSON.c\n"
"INCLUDES := {%&titulo%}.h\n"
"\n"
"OUTHER_DIR_INCLUDE  :=\n"
"\n"
"INCLUDES_FOR_OUTPUT :=\n"
"\n"
"LIBRARY_NAME := lib$(NAME).a\n"
"CFLAGS = $(OUTHER_DIR_INCLUDE)\n"
"OBJETOS      := $(FUENTES:%.c=%.o)\n"
"\n"
"# -------- RULES ------------------\n"
"\n"
"all: compila test\n"
"\n"
"compila: $(LIBRARY_NAME)\n"
"\n"
"$(OBJETOS):$(FUENTES) $(INCLUDES)\n"
"\n"
"$(LIBRARY_NAME): $(OBJETOS)\n"
"	- rm -f $(LIBRARY_NAME)\n"
"	ar -rf $@ $^\n"
"\n"
"clean:\n"
"	- rm -f $(OBJETOS) $(LIBRARY_NAME)\n"
"\n"
"test:\n"
"	make -f makefileTest\n";
