char *metaTab_h =
"{{={% %}=}}{%#ignore%}\n"
"   #ignore: esta seccion\n"
"   #tabla : seccion de recorrer toda la tabla\n"
"   #char  : datos de tipo char, solo uno\n"
"   #list  : datos de tipo list, solo uno\n"
"   #object : datos de tipo object, solo uno\n"
"   #itemObjeto : seccion de items de objeto\n"
"   &titulo : titulo de la tabla\n"
"   &name : nombre del elemento\n"
"   &lenChar : longitud de char\n"
"   &lenLista : longitud de la lista\n"
"   &itemObjeto.name : nombre de item objeto\n"
"   &itemObjeto.len : len de item objeto{%/ignore%}\n"
"/******************************************/\n"
"/*  Estructuras de la tabla {%&titulo%}  */ \n"
"/******************************************/{%#tabla%}{%#object%}\n"
"\n"
"/* Tabla {%&name%} */\n"
"\n"
"typedef struct { {%#itemObjeto%} \n"
" char {%&itemObjeto.name%}[{%&itemObjeto.len%}+1];{%/itemObjeto%}\n"
"} {%&name%}_t; {%/object%}{%/tabla%}\n"
"\n"
"/*  Estructura de la tabla {%&titulo%}  */ \n"
"\n"
"typedef struct {{%#tabla%} {%#char%} \n"
" char {%&name%}[{%&lenChar%}+1];{%/char%}{%#list%}\n"
" char {%&name%}[{%&lenLista%}][{%&lenChar%}+1];{%/list%}{%#object%}\n"
" {%&name%}_t {%&name%}; {%/object%} {%/tabla%}\n"
"} {%&titulo%}_t;\n"
"\n";
