char *metaTab_h =
"#define TIPO_ITEM(nTabla,nItem) ((nTabla)->tabla->item[(nItem)].tipo )\n"
"#define DATA_ITEM(nTabla,nItem) ((nTabla)->tabla->item[(nItem)].data )\n"
"\n"
"typedef struct\n"
"{\n"
" char nombre[200+1];\n"
" char descri[200+1];\n"
" int lenChar;\n"
"} itemChar_t;\n"
"typedef struct\n"
"{\n"
" char nombre[200+1];\n"
" char descri[200+1];\n"
" int lenLista;\n"
" int lenChar;\n"
"} itemLista_t;\n"
"typedef struct\n"
"{\n"
" char nombre[200+1];\n"
" char descri[200+1];\n"
" itemChar_t *item;\n"
" int numItems;\n"
"}itemObjeto_t;\n"
"\n"
"\n"
"/* Esta estructura es para la descripcion de un meta */\n"
"\n"
"typedef struct\n"
"{\n"
" char *descri;\n"
" char *tipo;\n"
" int lenChar;\n"
" int lenLista;\n"
"}itemMeta_t;\n"
"\n"
"// definira una linea en la estructura de tipo : tipo (*nombre)()\n"
"// por ejemplo int (* cbProceso)();\n"
"//cbProceso:Y:callback de proceso:int\n"
"//La tabla tendra esta pinta:\n"
"// cbProceso:appProceso\n"
"// El asignamiento sera:\n"
"// cbProceso=appProceso:\n"
"// Para realizar el test , habra que crear un : int appProceso(){}\n"
"typedef struct\n"
"{\n"
"char nombre[200+1];\n"
"char descri[200+1];\n"
"char tipo[200+1];\n"
"}itemCallBack_t;\n"
"\n"
"typedef struct\n"
"{\n"
"  char tipo;\n"
"  void *data;\n"
"} metaTabItem_t;\n"
"typedef struct\n"
"{\n"
" char titulo[100+1];\n"
" int numItems; \n"
" metaTabItem_t *item;\n"
"} metaTab_t;\n"
"\n"
"char *getNombreItemTabla(metaTab_t *tabla,int itemTabla);\n"
"char *getDescriItemTabla(metaTab_t *tabla,int itemTabla);\n"
"int  getLenCharItemTabla(metaTab_t *tabla,int itemTabla);\n"
"int  getLenListaItemTabla(metaTab_t *tabla,int itemTabla);\n"
"char *getNombreItemObjeto(metaTab_t *tabla,int itemTabla,int numItemObjeto);\n"
"char *getDescriItemObjeto(metaTab_t *tabla,int itemTabla,int numItemObjeto);\n"
"int getLenCharItemObjeto(metaTab_t *tabla,int itemTabla,int numItemObjeto);\n"
"int  getNumItemsObjeto(metaTab_t *tabla,int itemTabla);\n"
"char *getTipoItemCallBack(metaTab_t *tabla,int itemTabla);\n"
"int getMeta(metaTab_t *metaTab,char *label,char *labelItem,itemMeta_t *itemMeta);\n"
"\n"
"\n";
